base:
  botName: "悠里"
  botSelfId: 1234567
  adminList:
    - 1234567
command:
  prefix: "."
plugin:
  eroticPic:
    api: "https://api.lolicon.app/setu/v2"
    cdTime: 60
    recallMsgPicTime: 30
  repeat:
    thresholdValue: 5
  httpCat:
    api: "https://http.cat/"
