base: # 基础设置
  botName: "悠里" # 设置机器人昵称
  botSelfId: 123456789 # 设置机器人账号
  adminList: # 管理员列表
    - 123456789
    - 987654321
  searchMode:
    timeout: 30
plugin: # 插件设置
  animePic: # 色图插件
    r18: true  # 是否允许请求 r18 色图
    cdTime: 60 # 冷却时间（单位秒）
    recallMsgPicTime: 30 # 图片撤回时间（单位秒）
    proxy: "i.pixiv.re"
  repeat: # 复读姬插件
    waitTime: 60 # 多长时间内不复读重复内容（单位秒）
    thresholdValue: 5 # 复读阈值
  whatAnime: # 番剧检索
    sendPreviewVideo: true # 是否发送预览视频
  sauceNao:
    key: ""
  epic:
    cacheTime: 600 # 缓存时间 （这里为10分钟）
  tarot:
    cdTime: 60 # 冷却时间（单位秒）