base:
  # 设置机器人昵称
  botName: "悠里"
  # 设置机器人账号
  botSelfId: 123456789
  # 管理员列表
  adminList:
    - 123456789
    - 987654321
  searchMode:
    # 搜图模式超时时间
    timeout: 30
  # 启用仅群组白名单模式
  enableGroupOnlyWhiteList: false
plugin:
  picSearch:
    # 相似度低于多少自动调用Ascii2d搜图（自动转为 Float 类型）
    similarityLimit: "60"
    # 始终使用Ascii2d搜图（该设置为 true 时 similarityLimit 不生效）
    alwaysUseAscii2d: false
  animePic:
    # 是否允许请求 r18 色图
    r18: true
    # 冷却时间（秒）
    cdTime: 60
    # 图片撤回时间（秒）
    recallMsgPicTime: 30
    # 代理地址
    proxy: "i.pixiv.re"
  repeat:
    # 多长时间内不复读重复内容（秒）
    waitTime: 60
    # 复读阈值
    thresholdValue: 5
  whatAnime:
    # 是否发送预览视频
    sendPreviewVideo: true
  sauceNao:
    key: ""
  epic:
    # 缓存时间（秒）
    cacheTime: 600
  tarot:
    # 冷却时间（秒）
    cdTime: 60
  animeCrawler:
    # 开启调用限速
    enable: true
    # 每分钟可调用的次数（例如设置为 6 则是 10 秒允许调用一次）
    permitsPerMinute: 6
  roulette:
    # 超时（秒）
    timeout: 60
    # 最大禁言时间（分钟）
    maxMuteTime: 5
