server:
  port: 5555

logging:
  level:
    com.kennycason.kumo: OFF
  file:
    name: logs/yuri.log

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

shiro:
  plugin-list:
    - com.mikuac.yuri.plugins.initiative.Poke
    - com.mikuac.yuri.plugins.passive.GroupAddRequest

