server:
  port: 5555

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:BotDB.sqlite3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

shiro:
  plugin-list:
    - com.mikuac.yuri.plugins.aop.EventLog
    - com.mikuac.yuri.plugins.filter.TencentBotFilter
    - com.mikuac.yuri.plugins.BlackListCheck
    - com.mikuac.yuri.plugins.aop.AnimePic
    - com.mikuac.yuri.plugins.aop.Help
    - com.mikuac.yuri.plugins.Poke
    - com.mikuac.yuri.plugins.Repeat
    - com.mikuac.yuri.plugins.GroupJoinAndQuit
    - com.mikuac.yuri.plugins.aop.HttpCat
    - com.mikuac.yuri.plugins.aop.BvToAv
    - com.mikuac.yuri.plugins.aop.BotStatus
    - com.mikuac.yuri.plugins.aop.GithubRepo
    - com.mikuac.yuri.plugins.aop.WhatAnime
    - com.mikuac.yuri.plugins.aop.SauceNao
    - com.mikuac.yuri.plugins.aop.EpicFreeGame
    - com.mikuac.yuri.plugins.aop.PhoenixWright
    - com.mikuac.yuri.plugins.aop.ThrowUser
