server:
  port: 5555

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:BotDB.sqlite3
    hikari:
      maximum-pool-size: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

shiro:
  plugin-list:
    - com.mikuac.yuri.plugins.initiative.Poke
    - com.mikuac.yuri.plugins.initiative.GroupJoinAndQuit

