server:
  port: 5555

shiro:
  ws:
    server:
      enable: true

logging:
  level:
    com.kennycason.kumo: OFF
  file:
    name: logs/yuri.log

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    # database-platform: org.hibernate.community.dialect.SQLiteDialect

